spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/microservices
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.andreaswidii.user : DEBUG
